package forward

dialect "java"

import com.ftn.sbnz.model.models.PillowcaseFabric
import com.ftn.sbnz.model.models.FabricRecommendation
import com.ftn.sbnz.model.util.PillowcaseUtils

rule "Pillowcase calculation"
when
    $pf : PillowcaseFabric(
        getFabricCategory() == "HOME_DECOR"
    )
then
    double meters = PillowcaseUtils.pillowcaseMeters(
        $pf.getLength(),
        $pf.getWidth(),
        $pf.getFabricWidth()
    );

    insert(new FabricRecommendation(
        $pf.getFabric(),
        meters,
        "Jastučnica – dužina " + $pf.getLength() +
        " cm, širina " + $pf.getWidth() + " cm"
    ));
end
