spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/krojac_db
    username: postgres
    password: njusko123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
